version: '3.7'

services:
    fast_service:
        build:
            context: ./fast_service
            target: debug
        image: fast_service:0.0.1
        container_name: fast_service
        ports:
            - 8001:8000
            - 5678:5678
        # environment: 
        #     - DATABASE_URI=postgresql://user_db_username:user_db_password@user_db/user_db_dev
        # depends_on: 
        #     - user_db
    nginx:
        image: nginx:1.19.2
        container_name: nginx
        ports:
            - 8080:8080
        volumes:
            - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - fast_service
    