version: '3.7'

services:
    fast_service:
        build:
            context: ./fast_service
            target: prod
        image: fast_service:0.0.1
        container_name: fast_service
        ports:
            - 8001:8000
            - 5678:5678
        # environment: 
        #     - DATABASE_URI=postgresql://user_db_username:user_db_password@user_db/user_db_dev
        # depends_on: 
        #     - user_db
    nginx:
        image: nginx:1.19.2
        container_name: nginx
        ports:
            - 8080:8080
        volumes:
            - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - fast_service

    fluentd:
        container_name: fluentd
        user: root
        build:
            context: ./fluentd
        image: fluentd
        volumes:
        - /var/lib/docker/containers:/fluentd/log/containers # Example: Reading docker logs
        - ./fluentd/file:/fluentd/log/files/ #Example: Reading logs from a file
        - ./fluentd/configurations:/fluentd/etc/
        - ./fluentd/logs:/output/ # Example: Fluentd will collect logs and store it here for demo
        logging:
            driver: "local"

    elasticsearch: # port 9200
        image: elasticsearch:7.9.1
        container_name: elasticsearch
        environment:
            - node.name=elasticsearch
            - cluster.initial_master_nodes=elasticsearch
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports: 
            - 9200:9200
            - 9300:9300
        ulimits:
            memlock:
                soft: -1
                hard: -1
    kibana:
        image: kibana:7.9.1
        container_name: kibana
        ports:
            - "5601:5601"
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    